name: Generate GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # cada día
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Stats
        uses: jstrieb/github-stats@v1
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git commit -m "Update stats" || echo "No changes"
          git push
